/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Vipul' at '7/22/18 7:42 PM' with Gradle 2.0
 *
 * @author Vipul, @date 7/22/18 7:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
